# Generated by Django 3.0.4 on 2020-03-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_create_time', models.DateTimeField(blank=True, null=True)),
                ('b_modify_time', models.DateTimeField(blank=True, null=True)),
                ('b_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('b_title', models.CharField(blank=True, max_length=255, null=True)),
                ('b_content', models.TextField(blank=True, null=True)),
                ('b_read_num', models.IntegerField(blank=True, default=0, null=True)),
                ('u', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'db_table': 't_blog',
                'managed': True,
            },
        ),
    ]
