# Generated by Django 3.0.4 on 2020-03-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_tel', models.CharField(blank=True, max_length=11, null=True)),
                ('u_email', models.CharField(blank=True, max_length=20, null=True)),
                ('u_nike_name', models.CharField(blank=True, max_length=20, null=True)),
                ('u_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('u_is_delete', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': True,
            },
        ),
    ]
