# Generated by Django 3.0.4 on 2020-03-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_create_time', models.DateTimeField(blank=True, null=True)),
                ('c_content', models.CharField(blank=True, max_length=255, null=True)),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog')),
                ('u', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'db_table': 't_comment',
                'managed': True,
            },
        ),
    ]
